"""rename department

Revision ID: 55eda272d7d2
Revises: 6f339a0c967f
Create Date: 2024-07-25 19:00:06.455446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55eda272d7d2'
down_revision = '6f339a0c967f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###